version: "3.7"

services:
      
  sample-topology:
    tty: true
    build:
      context: ./
      dockerfile: ./sample-topology/Dockerfile
    image: frinx/fm-sample-topology:${RELEASE_VERSION}
    container_name: sample-topology
    environment:
      - JAVA_MAX_MEM=4G
    volumes:
        - uniconfig_pass:/opt/uniconfig_pass:ro
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"

volumes:
  uniconfig_pass:
      name: uniconfig_pass
      
networks:
  default:
    external:
      name: FRINX-machine
