version: "3.7"

x-extra_hosts: &extra_hosts_entries
        - "sample-topology:127.0.0.1"
        - "conductor-server:127.0.0.1"
        - "uniconfig:127.0.0.1"
        - "micros:127.0.0.1"
        - "dynomite:127.0.0.1"
        - "dyno1:127.0.0.1"
        - "elasticsearch:127.0.0.1"
        - "es:127.0.0.1"
        - "kibana:127.0.0.1"
        - "logstash:127.0.0.1"
        - "uniconfig-ui:127.0.0.1"
        - "portainer:127.0.0.1"
        - "sample-topology:::1"
        - "conductor-server:::1"
        - "uniconfig:::1"
        - "micros:::1"
        - "dynomite:::1"
        - "dyno1:::1"
        - "elasticsearch:::1"
        - "es:::1"
        - "kibana:::1"
        - "logstash:::1"
        - "uniconfig-ui:::1"
        - "portainer:::1"
services:
  sample-topology:
    build:
      context: ./
      dockerfile: ./sample-topology/Dockerfile
    image: frinx/fm-sample-topology:${RELEASE_VERSION}
    container_name: sample-topology
    volumes:
        - uniconfig_pass:/opt/uniconfig_pass:ro
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    network_mode: "host"
    extra_hosts: *extra_hosts_entries

  uniconfig:
    tty: true
    image: frinx/fm-uniconfig:${RELEASE_VERSION}
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    container_name: uniconfig
    environment:
      - JAVA_MAX_MEM=4G
    volumes:
       - uniconfig_logs:/opt/uniconfig-frinx/log
       - uniconfig_pass:/opt/uniconfig-frinx/db-credentials
       - uniconfig_data:/opt/uniconfig-frinx/data
    ports:
      - 8181:8181
    network_mode: "host"
    extra_hosts: *extra_hosts_entries

volumes:
  uniconfig_logs:
    name: uniconfig_logs
  uniconfig_pass:
      name: uniconfig_pass
  uniconfig_data:
      name: uniconfig_data

networks:
  default:
    external:
      name: FRINX-machine
