version: "3.7"

services:
      
  sample-topology:
    image: frinx/sample-topology:1.6
    environment:
      - JAVA_MAX_MEM=4G
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    healthcheck:
      test: /home/topology/healthcheck.sh
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy:
      # placement:
      #   constraints:
      #     - node.hostname == ${CONSTRAINT_HOSTNAME}
      mode: replicated
      replicas: 1
  
  demo-workflows:
    image: frinx/demo-workflows:1.6
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    environment:
      - UNICONFIG_URL_BASE=https://uniconfig:8181/rests
    healthcheck:
      test: cat /home/app/healthcheck && curl --silent --fail --write-out 'HTTPSTATUS:%{http_code}' -X GET 'http://workflow-proxy:8088/probe/readiness'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 50s
    deploy:
      # placement:
      #   constraints:
      #     - node.hostname == ${CONSTRAINT_HOSTNAME}
      mode: replicated
      replicas: 1

networks:
    default:
        external: true
        name: frinx-machine