version: "3.7"

x-logging: &logging_loki
    driver: loki
    options:
      loki-url: "http://${MANAGER_IP_ADDR}:3100/loki/api/v1/push"
      max-file: "3"
      max-size: "10m"
      loki-retries: "1"
      loki-batch-size: "1500"
      loki-relabel-config: |
        - action: labelmap
          regex: swarm_(service)

services:
  sample-topology:
    image: frinx/sample-topology
    logging: *logging_loki
    tty: true
    # cap_add Allow use iptables
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ${DIR_PATH}:/sample-topology
    environment:
      - DOCKER_GWBRIDGE_IP=${DOCKER_GWBRIDGE_IP}
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
    - ${PORT_RANGE_NETCONF}
    - ${PORT_RANGE}
    command:
      bash -c "${RUN_TESTTOOLS}"

networks:
    default:
      external: true
      name: frinx-machine



